management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
  health:
    db:
      enabled: false
    diskspace:
      enabled: true

