[tool.poetry]
name = "tutorial"
version = "0.1.0"
description = ""
authors = ["yoosc89 <yoosc89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pandas = "^2.1.2"
numpy = "^1.26.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
tete = "test:run"


