create table TBL_MEMBER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    PWD VARCHAR(255) NOT NULL ,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATE_AT TIMESTAMP NULL DEFAULT NULL,
    DELETE_AT TIMESTAMP NULL DEFAULT NULL,
    primary key (ID),
    unique key (USER_ID)
);

create table TBL_TEST (
      ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
      NAME VARCHAR(100) NOT NULL,
      AGE INT NOT NULL,
      EMAIL VARCHAR(255) NOT NULL,
      CREATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UPDATE_AT TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
      DELETE_AT TIMESTAMP NULL,
      REF_MEMBER_ID BIGINT NOT NULL,
      CONSTRAINT FOREIGN KEY (REF_MEMBER_ID) REFERENCES TBL_MEMBER (ID)
);