

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: test1
      password: test1
      database: test
      authentication-database: test
      #uri: mongodb://test:test@localhost:27017/test
#  main:
#    allow-bean-definition-overriding: true
server:
  port: 8090
