/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mono;

import java.util.ArrayList;
import java.util.List;

import reactor.core.publisher.Flux;

public class App {
    public static void main(String[] args) {
        Long startTime = 0L;
        Long endTime = 0L;
        List<Integer> test1 = new ArrayList<>();

        for (int i = 0; i < 100000000; i++) {
            test1.add(i);
        }

        Flux<Integer> test = Flux.fromIterable(test1);

        System.out.println("------------------");
        startTime = System.currentTimeMillis();
        test.subscribe(e -> {
            // System.out.println(e);
        });
        endTime = System.currentTimeMillis();
        System.out.println("------------------");
        System.out.println(endTime - startTime);
        System.out.println("------------------");

        System.out.println("------------------");
        startTime = System.currentTimeMillis();
        for (Integer i : test1) {
            // System.out.print(i);
        }
        endTime = System.currentTimeMillis();
        System.out.println("------------------");
        System.out.println(endTime - startTime);
    }
}
