/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jmh;

import org.junit.jupiter.api.Test;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.State;

@State(Scope.Benchmark)
@BenchmarkMode({ Mode.All })
@OutputTimeUnit(java.util.concurrent.TimeUnit.MILLISECONDS)
class AppTest {

    @Test
    @Benchmark
    void appHasAGreeting() {
        CompareTimer compareTimer = new CompareTimer();

        for (int loop = 0; loop < 10; loop++) {
            compareTimer.checkCurrentTimeNanos();
            compareTimer.checkCurrentTimeMillils();
        }
    }
}
